# Generated by Django 3.2.21 on 2023-10-19 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='captchaCpde',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.ImageField(default='', upload_to='img/gurkul_admin/captchaImgs')),
                ('value', models.CharField(default='', max_length=5)),
            ],
        ),
    ]
