# Generated by Django 3.2.21 on 2023-10-19 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captchacpde',
            name='image',
            field=models.ImageField(default='', upload_to='img/captchaImgs'),
        ),
    ]
