# Generated by Django 3.2.21 on 2023-10-21 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0003_allproducts_productscart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allproducts',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
