# Generated by Django 3.2.21 on 2023-10-21 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0004_alter_allproducts_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='allproducts',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
