# Generated by Django 3.2.21 on 2023-10-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0005_allproducts_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscart',
            name='prod_ids',
            field=models.JSONField(default=''),
        ),
    ]
