# Generated by Django 4.2.6 on 2023-10-22 03:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('testingApp', '0008_alter_productscart_prod_ids'),
    ]

    operations = [
        migrations.CreateModel(
            name='productComment',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('product_id', models.IntegerField(default=0)),
                ('comment', models.TextField(default='', max_length=200)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('usrname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
