# Generated by Django 4.2.6 on 2023-10-22 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0009_productcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='productComment',
        ),
    ]
